version: "3.9"
services:
    redis:
        container_name: redis
        hostname: redis
        networks:
            - server-network
        image: redis
        ports:
            - 6379:6379

    mysql:
        ports:
            - "3306:3306"
        container_name: mysql
        image: mysql:latest
        restart: always
        networks:
            - server-network
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        volumes:
            - ./docker/mysql:/var/lib/mysql

    nginx:
        image: nginx:alpine
        container_name: nginx
        working_dir: /
        volumes:
            - ./:/var/www
            - ./docker/nginx:/etc/nginx/conf.d
        ports:
            - "80:80"
        networks:
            - server-network

    php-82:
        build: docker/php
        container_name: php
        working_dir: /
        volumes:
            - ./:/var/www
        networks:
            - server-network

networks:
    server-network:
        external: true
